pipeline {

    agent any

    tools {
        nodejs '20.3.0'
    }

    environment {
        SONAR_SCANNER = tool 'SonarScaner'
        DOCKER_HUB_CREDENTIALS = 'dockerHub'
        DOCKER_IMAGE_NAME = 'aalegre25/express-node'
        DOCKER_IMAGE_TAG = "$BUILD_NUMBER" 
    }

    stages {

        stage ('Compilar'){
            steps {
                echo 'Compilando ....'
                sh 'npm install'
            }
        }

        stage ('Pruebas'){
            steps {
                echo 'Pasando las pruebas ....'
                sh 'npm test'
            }
        }

        stage('Análisis de código estático') {
            steps {
                
                echo 'Analizando código con SonarQube...'

                withSonarQubeEnv('sonarqube-server') {
                    sh "${SONAR_SCANNER}/bin/sonar-scanner -Dproject.settings=devops/sonar.properties"
                }

                timeout(time: 2, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('Build') {
            steps {
                echo 'Generando build...'
                sh "docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG} ." 
            }
        }

        stage('Publicar imagen'){

            steps {
                echo 'Publicando imagen...'

                withCredentials([usernamePassword(credentialsId: DOCKER_HUB_CREDENTIALS, passwordVariable: 'DOCKERHUB_PASSWORD', usernameVariable: 'DOCKERHUB_USERNAME')]) {
                    script {
                        def dockerHubRegistry = "docker.io" 
                        sh "docker login -u ${DOCKERHUB_USERNAME} -p ${DOCKERHUB_PASSWORD} ${dockerHubRegistry}"
                        sh "docker push ${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}"
                    }
                }
            }

        }

        stage('Ejecutar imagen de Docker en servidor remoto') {
            steps {
                script {
                    def Docker = require('dockerode');
                    def docker = new Docker({ host: '194.163.150.189', port: 2376, ca: credentials('docker_ca').file, cert: credentials('docker_client').file, key: credentials('docker_client-key').file });
                    
                    // Nombre de la imagen de Docker que quieres ejecutar
                    def dockerImage = "${DOCKER_IMAGE_NAME}:${DOCKER_IMAGE_TAG}";
                    
                    // Detener y eliminar cualquier contenedor previo con el mismo nombre en el servidor remoto
                    docker.getContainer('express').stop()
                      .then(() => docker.getContainer('express').remove())
                      .catch(() => {}) // Ignorar si el contenedor no existe

                    def portBindings = {
                        "3000/tcp": [{ "HostPort": "3000" }]
                    };
                    
                    // Ejecutar la imagen de Docker en el servidor remoto
                    docker.createContainer({ Image: dockerImage, name: 'express', HostConfig: { PortBindings: portBindings } })
                      .then(container => container.start())
                      .catch(error => console.error('Error al ejecutar el contenedor:', error))
                }
            }
        }
    }
    
}