version: "3"
services:
  dbnode:
    image: mysql:8.0.33
    container_name: dbnode
    networks:
      - nodered
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  express:
    image: aalegre25/express-sql:${BUILD_NUMBER}
    container_name: express
    ports:
      - "3000:3000"
    networks:
      - nodered
networks:
  nodered:
    ipam:
      config:
        - subnet: 172.25.0.0/24
# version: "3.3"

# services:
#   dbmysql:
#     image: mysql:latest
#     container_name: dbnode
#     #restart: always
#     environment:
#       MYSQL_DATABASE: "db"
#       MYSQL_USER: "user"
#       MYSQL_PASSWORD: "password"
#       MYSQL_ROOT_PASSWORD: "password"
#     ports:
#       - "3306:3306"
#     volumes:
#       - my-db:/var/lib/mysql
# volumes:
#   my-db:

# version: "3.8"

# services:
#   mysql:
#     image: mysql:8.0.33
#     container_name: tiendaNode
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: db
#       MYSQL_USER: user
#       MYSQL_PASSWORD: password
#     ports:
#       - "3306:3306"
# #     networks:
# #       - node

# # networks:
# #   node:
# #     name: node
# #     driver: bridge
