version: "3.8"

services:
  mysql:
    image: mysql:8.0.33
    container_name: tiendaNode
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - node

networks:
  node:
    name: node
    driver: bridge
