version: "3.3"

services:
  dbmysql:
    image: mysql:8.0.33
    container_name: tiendaNode
    restart: always
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - node
volumes:
  my-db:
networks:
  default:
    external:
      name: node
